import Header from "@/Components/header";
import Footer from "@/Components/footer";
import type { Metadata } from "next";
import {
  ralewayBlack,
  ralewayBold,
  ralewayExtrabold,
  ralewayMedium,
  ralewayRegular,
  ralewaySemibold,
} from '../fonts/fonts';
import "./globals.css";

export const metadata: Metadata = {
  title: "Escape room",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ralewayBlack.variable} ${ralewayBold.variable} ${ralewayExtrabold.variable} ${ralewayMedium.variable} ${ralewayRegular.variable} ${ralewaySemibold.variable} flex flex-col bg-[#1C1C1C] bg-[url('../assets/img/background.png')] w-full h-screen bg-no-repeat filter blur-15`}>
        <Header />
        <main className="overflow-y-auto ">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
